<?php
/**
 * Created by PhpStorm.
 * User: guilherme.zupolini
 * Date: 21/06/2017
 * Time: 14:12
 */
$form = $this->form;

?>

<div  class="alert" id="painelMsg" style="display: none;">
</div>


<fieldset>
    <legend><?php echo $form->getName() ?></legend>

    <?php echo $this->form()->openTag($form); ?>

    <div><?php echo $this->formInput($form->get('idCurso'))?></div>

    <div class="row">
        <div class="form-group col-md-5 col-xs-5">
            <?php echo $this->formLabel($form->get("noCurso")) ?>
            <?php echo $this->formInput($form->get("noCurso")) ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-5 col-xs-5">
            <?php echo $this->formLabel($form->get("sgCurso")) ?>
            <?php echo $this->formInput($form->get("sgCurso")) ?>
        </div>
    </div>

    <div class="pull-left">
        <button type="button" class="btn btn-default" id="btnNovo">Novo Curso</button>
        <button type="button" class="btn btn-primary" id="btnConsulta">Consultar</button>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</fieldset>

<hr>

<table id="tabelaConsulta">
<!--    <thead>-->
<!--        <tr>-->
<!--            <th style="text-align: center;">Nome</th>-->
<!--            <th style="text-align: center;">Sigla</th>-->
<!--            <th style="text-align: center;">Carga Horária</th>-->
<!--            <th style="text-align: center;">Ações</th>-->
<!--        </tr>-->
<!--    </thead>-->
<!---->
<!--    <tbody>-->
<!---->
<!--    </tbody>-->
</table>


<script>
    $(document).ready(function () {
//        $('#tabelaConsulta').DataTable();

        $('#btnNovo').on('click', function () {
            window.location.assign('/cadastro');
        });

        $('#btnConsulta').on('click', function () {
           $.ajax({
               datatype: 'JSON',
               url: "/consultar/consultarCurso",
               type: "GET",
               success: function (data) {
                   var retorno = JSON.parse(data);
                   console.log(retorno.dados);
                   var dataSet = [];
                   $.each(retorno.dados, function (index, data) {
                       dataSet.push([data.noCurso, data.sgCurso, data.chCurso])
                   });
                   $('#tabelaConsulta').DataTable({
                       data: dataSet,
                       columns: [
                           {title: 'Nome'},
                           {title: 'Sigla'},
                           {title: "CargaHoraria"}
                       ]
                   });
               }
           });
        });
    })
</script>