<?php
/**
 * Created by PhpStorm.
 * User: guilherme.zupolini
 * Date: 16/06/2017
 * Time: 10:25
 */

echo $this->headTitle($this->form->getName());
$form = $this->form;
//$form->prepare();
//echo "<pre>";var_dump($this->form);
?>


<!--<div class="col-xs-12">-->
<div  class="alert" id="painelMsg" style="display: none;">
</div>


    <fieldset>
        <legend><?php echo $form->getName() ?></legend>

        <?php echo $this->form()->openTag($form); ?>

        <div><?php echo $this->formInput($form->get('idCurso'))?></div>

        <div class="row">
            <div class="form-group col-md-5 col-xs-5">
                <?php echo $this->formLabel($form->get("noCurso")) ?>
                <?php echo $this->formInput($form->get("noCurso")) ?>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-5 col-xs-5">
                <?php echo $this->formLabel($form->get("sgCurso")) ?>
                <?php echo $this->formInput($form->get("sgCurso")) ?>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-5 col-xs-5">
                <?php echo $this->formLabel($form->get("chCurso")) ?>
                <?php echo $this->formInput($form->get("chCurso")) ?>
            </div>
        </div>

        <div class="pull-left">
            <button type="button" class="btn btn-default" id="btnCancelar">Cancelar</button>
            <button type="button" class="btn btn-primary" id="btnSalvar">Salvar</button>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </fieldset>

<!--</div>-->

<script>
    $(document).ready(function () {
        $('#chCurso').mask("9999");

        $('#btnSalvar').on('click', function () {
            $('#painelMsg').html("");
            if(validaCampos(['input'])){
//                alert('certo');

            $.ajax({
                url: '/cadastro/salvarCurso',
                datatype:'json',
                type: 'POST',
                data: $('form').serialize(),
                success: function (data) {
                    var retorno = JSON.parse(data);

                    if(retorno.status == "sucesso"){
                        voltarTopo();
                        msgAlerta(retorno.status, retorno.msg, '#painelMsg');
                        limparCampos(['input']);
                    }

                }
            });
            }else{
                voltarTopo();
                var msg = "Preencha os campos obrigatórios!";
                msgAlerta("erro", msg, '#painelMsg');
            }
        });
        $('#btnCancelar').on('click', function () {
            window.location.assign('/consultar');
        });
    })
</script>
